language: csharp
solution: AM.Common.RegularExpressions.sln
mono: none
dotnet: 2.0.0
script:
 - dotnet restore
 - dotnet build
 - dotnet test ./test/AM.Common.RegularExpressions.Tests/AM.Common.RegularExpressions.Tests.csproj
